### ISSUE TITLE
Text with umlauts is too close to the top edge

### ISSUE THREAD

**Issue by Kagami** [nomad-software/meme#8]
Example:

```bash
meme -i advice-mallard -t "ёёё|ттт"
```

![meme](https://cloud.githubusercontent.com/assets/533383/25086999/8ccdc410-2374-11e7-9ea8-570caa8e738e.png)

**Comment by nomad-software** [comment]
This is a tricky one because it's actually a feature (or limitation) of the [drawing library](https://github.com/fogleman/gg) I'm using.

I could compensate for this but it would mean maintaining a hardcoded list of letters to detect because there is no easy way of detecting these in the string programmatically, which isn't ideal. I think we are stuck with this for the time being.
